### ISSUE TITLE
Could you please support GUI Manager Module

### ISSUE THREAD

**Issue by takaaptech** [gmhevinci/MotionFramework#1]
Hi @gmhevinci ,
I found this MotionFramework is awesome for making games, thanks for sharing it!
I need a GUI Manager solution like this:
https://github.com/NicoleXiao/UIFramework
Could you please add this or make a Module to control the Panel, Dialog Flow in-game.
Thank you in advance!

**Comment by gmhevinci** [comment]
hi @takaaptech 
i will release simple GUI module in next week. And remake demo1 for 'Indie' game developer.

**Comment by takaaptech** [comment]
Hi @gmhevinci That is awesome! Thank you!

**Comment by gmhevinci** [comment]
Hi @takaaptech The window module has been released in V1.2.0
enjoy yourself ~~

**Comment by takaaptech** [comment]
Hi @gmhevinci , Thank you very much!
