### ISSUE TITLE
ReferencePool的ClearAll函数实现?

### ISSUE THREAD

**Issue by lexnewgate** [gmhevinci/MotionFramework#10]
https://github.com/gmhevinci/MotionFramework/blob/5a626d792256bf30b94fab605e5ebb56bd89fc09/Assets/MotionFramework/Scripts/Runtime/Engine/Engine.Reference/ReferencePool.cs#L41-L44

这段代码应该可以直接删掉吧?

**Comment by gmhevinci** [comment]
目前没有用到

**Comment by lexnewgate** [comment]
@gmhevinci  哦 你可能误解我的意思了. 我的意思是
https://github.com/gmhevinci/MotionFramework/blob/5a626d792256bf30b94fab605e5ebb56bd89fc09/Assets/MotionFramework/Scripts/Runtime/Engine/Engine.Reference/ReferencePool.cs#L45
这个已经包含了上面的含义,就不用多走一个循环了.

**Comment by gmhevinci** [comment]
ReferenceCollector类的Clear方法内部没有特殊处理，的确可以移除掉。
