### ISSUE TITLE
_buildinTags 是用来定基础版本用的么?

### ISSUE THREAD

**Issue by lexnewgate** [gmhevinci/MotionFramework#13]
https://github.com/gmhevinci/MotionFramework/blob/8ffb6aced84a388be9d987dab6a53a0240ceb7dd/Assets/MotionFramework/Scripts/Editor/AssetBundleBuilder/AssetBundleBuilderWindow.cs#L88

这个`_buildinTags ` 的作用是用来定基础版本用的么? 就是每次发整包写一个tag. 这样不同版本不会混淆?

**Comment by gmhevinci** [comment]
这个是用来做DLC资源的，具体可以参考Project-Patch工程。

**Comment by gmhevinci** [comment]
欢迎你加入QQ群654986302，随时随地的可以学习讨论。

**Comment by lexnewgate** [comment]
> 欢迎你加入QQ群654986302，随时随地的可以学习讨论。

在群里潜水中...

issue先关掉了. 等看完Project-Patch有疑问再打开.
