### ISSUE TITLE
MotionFramework/ThirdParty/Compatibility/AssetBundleCollectorSetting.cs脱离了程序集的管理

### ISSUE THREAD

**Issue by code-hasaki** [gmhevinci/MotionFramework#19]
MotionFramework/ThirdParty/Compatibility/AssetBundleCollectorSetting.cs
MotionFramework/ThirdParty/YooAsset/Editor/AssetBundleCollector/AssetBundleCollectorSetting.cs
第一个路径是不是没用了，现在用第二个路径的？

**Comment by gmhevinci** [comment]
是的。第一个路径的文件是为了兼容老版本
