### ISSUE TITLE
一个小建议,ResourceManager底层能否加一个每帧LoadAssetAsync的数量限制

### ISSUE THREAD

**Issue by code-hasaki** [gmhevinci/MotionFramework#3]
用100个配置做测试ConfigManager.LoadConfigs(List<LoadPair> loadPairs),
第1个回调会在2秒后才触发, 后续99个回调会在第1个回调后面正常陆续触发,
也就是说, 虽然unity主线程不会卡顿, 但是ab线程应该是卡住了.
后来我在逻辑层把Load的数量控制在每帧10个以内, 才感觉正常.
正常是指: 不管逻辑层同时load多少个ab, 第1个回调都应该正常触发

**Comment by gmhevinci** [comment]
不错的建议，我会在下次release里加入这个功能。

**Comment by gmhevinci** [comment]
See new release
