### ISSUE TITLE
关于资源同步加载的疑问

### ISSUE THREAD

**Issue by cLockey** [gmhevinci/MotionFramework#6]
AssetBundleLoader.ForceSyncLoad()
`
while (true)
{
        *******
	Update();
        *******
}
`
请教一下，这里为什么采用挂起主线程，异步加载，而不用AssetBundle.LoadFromFile()的方式？

**Comment by gmhevinci** [comment]
同步加载已经优化完毕了。目前是同步和异步方法混用。while()循环是为了驱动FileLoader的Update方法，理论上只需要驱动几次就可以完成加载。while()循环不会造成卡顿。
