### ISSUE TITLE
BuildContext设计思路?

### ISSUE THREAD

**Issue by lexnewgate** [gmhevinci/MotionFramework#8]
https://github.com/gmhevinci/MotionFramework/blob/5a626d792256bf30b94fab605e5ebb56bd89fc09/Assets/MotionFramework/Scripts/Editor/AssetBundleBuilder/BuildSystem/BuildContext.cs#L12

`BuildContext` 这个类存在的主要目的是为了
https://github.com/gmhevinci/MotionFramework/blob/5a626d792256bf30b94fab605e5ebb56bd89fc09/Assets/MotionFramework/Scripts/Editor/AssetBundleBuilder/AssetBundleBuilder.cs#L170
执行的方便性么? 或者说 `BuildContext`是一种每次运行清零的单例管理器?

**Comment by gmhevinci** [comment]
主要是为了临时保存每个节点的产生的数据。重新构建的时候需要清空。
